plugins {
	id 'java'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.boop.core'
version = '0.0.1-SNAPSHOT'
description = 'Core library for Boop Application'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

ext {
	springBootVersion = '4.0.6'
	openApiVersion = '3.0.2'
	grpcStarterVersion = '3.1.0.RELEASE'
}


repositories {
	mavenCentral()
}

dependencies {
	implementation project(':boop-api')

	implementation platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
	implementation "org.springdoc:springdoc-openapi-starter-common:${openApiVersion}"

	implementation "net.devh:grpc-client-spring-boot-starter:${grpcStarterVersion}"
	implementation "net.devh:grpc-server-spring-boot-starter:${grpcStarterVersion}"

	implementation 'io.micrometer:micrometer-core'

	implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'
	implementation 'org.springframework.security:spring-security-oauth2-jose'

	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile) {
	options.compilerArgs += ['-Xlint:deprecation']
	options.compilerArgs += ['-Xlint:unchecked']
}

tasks.named('test') {
	useJUnitPlatform()
}