server.port: 8083

spring:
  application:
    name: boop-service-marketplace
  http:
    codec:
      log-request-details: true
  datasource:
    url: jdbc:postgresql://${db.host}:5432/${POSTGRES_DB}?sslmode=disable
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  info:
    developer:
      name: Alex Kumpel
      email: deathkid777@gmail.com
    api:
      version: 1.0

management:
  endpoints:
    web:
      base-path: /service-marketplace-actuator
      exposure:
        include: "*"
  endpoint:
    configprops:
      show-values: always
    health:
      show-details: always
      status:
        order: events-down, fatal, down, out-of-service, unknown, up
    shutdown:
      enabled: true
    info:
      env:
        enabled: true

db.host: localhost

jwt:
  auth:
    converter:
      resource-id: boop-application-client
      principle-attribute: preferred_username

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.boot.autoconfigure: INFO


springdoc:
  packages-to-scan: com.boop.service.marketplace
  paths-to-match: /**
  cache.disabled: true
  api-docs:
    path: /service-marketplace/openapi/v3/api-docs
  swagger-ui:
    enabled: true
    path: /service-marketplace/openapi/swagger-ui.html

---
spring.config.activate.on-profile: docker
spring.data.redis.host: redis
server.port: 80
db.host: postgres
#db.host: postgres.hands-on.svc.cluster.local

---
spring.config.activate.on-profile: prod
db.host: host.minikube.internal