server.port: 8082

spring:
  application:
    name: boop-pet-specialists
  http:
    codec:
      log-request-details: true
  datasource:
    url: jdbc:postgresql://${db.host}:5432/${POSTGRES_DB}?sslmode=disable
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  info:
    developer:
      name: Alex Kumpel
      email: deathkid777@gmail.com
    api:
      version: 1.0
grpc:
  client:
    keycloakAdmin:
      address: static://keycloak-admin:9090
      negotiationType: plaintext

management:
  endpoints:
    web:
      base-path: /specialists-actuator
      exposure:
        include: "*"
  endpoint:
    configprops:
      show-values: always
    health:
      show-details: always
      status:
        order: events-down, fatal, down, out-of-service, unknown, up
    shutdown:
      enabled: true
    info:
      env:
        enabled: true

db.host: localhost

jwt:
  auth:
    converter:
      resource-id: boop-application-client
      principle-attribute: preferred_username

logging:
  level:
#    org.springframework.security: INFO
#    org.springframework.web: INFO
#    org.springframework.boot.autoconfigure: INFO


springdoc:
  packages-to-scan: com.boop.specialists
  paths-to-match: /**
  cache.disabled: true
  api-docs:
    path: /specialists/openapi/v3/api-docs
  swagger-ui:
    enabled: true
    path: /specialists/openapi/swagger-ui.html
    oauth:
      clientId: ${KEYCLOAK_OAUTH_CLIENT_ID}
      clientSecret: ${KEYCLOAK_OAUTH_CLIENT_SECRET}
  oAuthFlow:
    authorizationUrl: http://${keycloak.host}:8080/realms/${keycloak.realm}/protocol/openid-connect/auth
    tokenUrl: http://${keycloak.host}:8080/realms/${keycloak.realm}/protocol/openid-connect/token

---
spring.config.activate.on-profile: docker
server.port: 80
db.host: postgres
#db.host: postgres.hands-on.svc.cluster.local

---
spring.config.activate.on-profile: prod
db.host: host.minikube.internal