server:
  port: ${PORT:8443}
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/boop-cert.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-alias: localhost

spring:
  application:
    name: boop-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${keycloak.host}:8080/realms/${keycloak.realm}
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_OAUTH_CLIENT_ID}
            client-secret: ${KEYCLOAK_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid,email,profile,roles
#        registration:
#          google:
#            # Google
#            client-id: [google_client_id]
#            client-secret: [google_client_secret]
#            redirect-uri: https://localhost:8443/login/oauth2/code/google
#            scope:
#              - openid
#              - email
#              - profile
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            user-name-attribute: sub
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
      server:
        webflux:
          routes:
            # pet-owner routes
            - id: admin
              uri: http://boop-pet-owners
              predicates:
                - Path=/api/admin/**
              filters:
                - name: CircuitBreaker
                  args:
#                    id: keycloakApiCircuitBreaker
                    name: KeycloakApiCircuitBreaker
                    fallbackUri: forward:/fallback
                    statusCodes:
                      - 500
                      - 503
                      - 404
                      #- 401

            - id: pet-owners
              uri: http://boop-pet-owners
              predicates:
                - Path=/api/pet-owners/**
              filters:
                - TokenRelay

            - id: pet-owners-swagger-ui
              uri: http://boop-pet-owners
              predicates:
                - Path=/owners/openapi/**
              filters:
                - TokenRelay

            - id: pet-owners-swagger-ui-webjars
              uri: http://boop-pet-owners
              predicates:
                - Path=/owners/webjars/**
              filters:
                - TokenRelay

            - id: pet-owners-actuator
              uri: http://boop-pet-owners
              predicates:
                - Path=/owners-actuator/**
              filters:
                - TokenRelay

            #pet-specialist routes
            - id: pet-specialists
              uri: http://boop-pet-specialists
              predicates:
                - Path=/api/pet-specialists/**
              filters:
                - TokenRelay

            - id: pet-specialists-swagger-ui
              uri: http://boop-pet-specialists
              predicates:
                - Path=/specialists/openapi/**
              filters:
                - TokenRelay

            - id: pet-specialists-swagger-ui-webjars
              uri: http://boop-pet-specialists
              predicates:
                - Path=/specialists/webjars/**
              filters:
                - TokenRelay

            #service marketplace routes
            - id: service-marketplace
              uri: http://boop-service-marketplace
              predicates:
                - Path=/api/service-marketplace/**
              filters:
                - TokenRelay

            - id: service-marketplace-swagger-ui
              uri: http://boop-service-marketplace
              predicates:
                - Path=/service-marketplace/openapi/**
              filters:
                - TokenRelay

            - id: service-marketplace-swagger-ui-webjars
              uri: http://boop-pet-service-marketplace
              predicates:
                - Path=/service-marketplace/webjars/**
              filters:
                - TokenRelay

            - id: keycloak-jwt-token
              uri: http://keycloak
              predicates:
                - Path=/realms/boop-app-realm/protocol/openid-connect/token

resilience4j:
  circuitbreaker:
    instances:
      keycloakApiCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 10s
    metrics:
      legacy:
        enabled: true
    enabled: true

management:
  endpoint:
    health:
      show-details: "ALWAYS"
    gateway:
      access: read_only

keycloak:
  auth-server-url: http://${keycloak.host}:8080
  client-id: ${KEYCLOAK_OAUTH_CLIENT_ID}
  client-secret: ${KEYCLOAK_OAUTH_CLIENT_SECRET}

springdoc:
  cache:
    disabled: true
  api-docs:
    path: /openapi/v3/api-docs
  swagger-ui:
    enabled: true
    path: /openapi/swagger-ui.html
    urls:
      - url: /openapi/v3/api-docs
        name: API Gateway Service
      - name: Pet Owners
        url: https://localhost:8443/owners/openapi/v3/api-docs
      - name: Pet Specialists
        url: https://localhost:8443/specialists/openapi/v3/api-docs
      - name: Service Marketplace
        url: https://localhost:8443/service-marketplace/openapi/v3/api-docs

logging:
  level:
#    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
#    org.springframework.security: TRACE
#    org.springframework.web: TRACE
#    org.springframework.boot.autoconfigure: TRACE